# Generated by Django 5.1.4 on 2024-12-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=32)),
                ('created_datetime', models.DateField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=64)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
